### ISSUE TITLE
destroy_map in Op for inplace

### ISSUE THREAD

**Issue by albertz** [Theano/Theano#3506]
You need to define what outputs destroys what input. Why is that? I would expect that it must only know which inputs would be destroyed after the inplace Op is applied.

In my case, if have a pure Op and an inplace Op, and for the inplace Op, multiple of the outputs will operate on some inputs (inputs 1 and 6). And I have an optimization registered that will apply the substitute the pure Op with the inplace Op.

So, for the inplace Op, I had something like `destroy_map = {0: [1,6], 1: [1,6]}` but that failed with some error.

Then, from the [docs](http://deeplearning.net/software/theano/extending/inplace.html), I understood that I maybe just can use an arbitrary output index, so I tried `destroy_map = {0: [1,6]}`. But in that case, it will not apply the inplace optimization anymore. Or it also fails with some error.

Now, I am using `destroy_map = {0: [1], 1: [6]}` and that seems to work. I.e. it applies the inplace optimization.

But this looks like three bugs to me:

1. The docs don't really explain why it is important for Theano to know which output operates on which inputs, and not just the list of inputs which will be destroyed.

2. Error when I specify some input index multiple times. This should work. Even one of the examples does this.

3. No correct inplace optimization in the case `destroy_map = {0: [1,6]}`.

---

I guess the relevant code is in [destroyhandler.py](https://github.com/Theano/Theano/blob/master/theano/gof/destroyhandler.py) in `_build_droot_impact()`.

**Comment by abergeron** [comment]
This is a question for the theano-dev mailing list not an issue.

As for your questions:

1. Theano needs to know which output uses which input to check for dependency cycles in the graph.  It might be possible to assume that all outputs depend on the destroyed inputs, but it is not what we currently do.

2. It is not supported to have multiple outputs work inplace on the same input (I'm not sure what operation would actually do this...).  Documentation is wrong and should be fixed.

3. It is not supported to have one output work inplace on multiple inputs since that does not make sense.  Documentation is wrong and should be fixed.

**Comment by albertz** [comment]
Thanks for the answer. I thought that this issue tracker is also for bugs in the documentation. But I also thought that this is a bug in Theano.

We actually have some Op where the calculation destroys some inputs (1 and 6). And the calculation produces all the outputs. So I cannot really say which output is operating on what input. And still not sure what to put in the `destroy_map`. Specific outputs also don't really work inplace on the inputs - the calculation just modifies them and thus destroy them.

Maybe this is also a feature request then. I also thought that the issue tracker would be the right place in that case.

If I'm wrong or I just don't understand it right, sorry, then really better let's move this discussion to the mailing list.

**Comment by abergeron** [comment]
Yes it is also for bugs in documentation or feature requests the bug tracker is fine, but not for questions.

This looked a lot like a question, but if you want to change to make that a documentation bug or a feature request, go ahead.

I do think that fixing the code to accept what you want will take quite some time, so the documentation has a greater chance of being fixed.

**Comment by nouiz** [comment]
For 1) I don't know why we need that and @abergeron explanation don't make me understand why we need the exact mapping. We use it in DebugMode to print warning when an op declared something but didn't have the output return a view of the destroyed inputs. If there is no other reason, then your working version should work correctly without hidden and corner case problems.

2) Currently, we support mostly the case where one output is the inplace of some operation on a given input. That is why we don't allow the same indices to be there multiple time. But can you confirm that your output do not return view of the input, your op just used the memory as temporary memory for computation?

3) This is a feature not implemented. It could be useful for our IfElse to be inplace on both branch. Currently we are inplace on the True branch and need to copy the data in the False branch. I suppose this would need change at a few places in Theano to implement correctly.

I'll reopen the ticket as there is change needed in Theano. @abergeron can you explain more your answer to 1? To be sure if @albertz work-around is safe or not.

**Comment by pv182253** [comment]
I'm working together with @albertz. 
The Op he's mentioned gets two inputs which are reused. One of them is just used as temporary memory and is not aligned with the outputs. The memory of the other one is returned as one output (fully aligned).
It would be good to know, if our workaround is safe. 
Recently with newer versions of theano we got an error which indicates a cycle in the graph, maybe this is related. With a bit older versions it just works fine.

**Comment by abergeron** [comment]
For 1) I mean that the current code needs that (aside from DebugMode).  As I mentioned it may be fixed to not require that but currently does.

So maybe we should change the dict to be a list and that could fix all your points.

**Comment by abergeron** [comment]
Also, we usually don't add an input for working memory and either keep a buffer around in the Op struct or allocate a new one at each run.  This might also solve your problem but not destroying two inputs.

If you actually need the values from both inputs, then we would have to change things to make it work.

**Comment by pv182253** [comment]
To clarify, we need the input not only for the memory but also the contents. But we modify it inplace to save memory and at the end it isn't needed anymore. So we do need the values from all inputs.

**Comment by nouiz** [comment]
@abergeron  for 1) why it is needed? That is my question. If i'm right, his work around is good. If you are right, his work around isn't good. So we should be sure that both of us have the same information!

**Comment by abergeron** [comment]
I would have to look at the code in destroyhandler to make sure why we need it.

**Comment by lamblin** [comment]
When Theano was designed, we did not think of the case you are mentioning: that some input may be destroyed for another purpose than to hold the value of an output. Therefore, `destroy_map` provides both informations at the same time: that an input is going to be destroyed, and that the corresponding output is going to be a view of that memory.
It is a flaw in the design, as it would make sense to specify the first one without the second one (the other way around is possible, using `view_map`).
Updating DestroyHandler, and maybe toposort, to handle those cases would be nice, but it may be long to do correctly without breaking anything, so we are not sure we can help in the near future.

In the mean time, your workaround should be OK, provided that the output that is a view of one of the destroyed inputs is actually matched with that input. For instance, if output 1 is seeing the memory of input 6, or if output 0 is seeing the memory of input 1, that should be fine.
