### ISSUE TITLE
segfault with dot, C linker

### ISSUE THREAD

**Issue by gophercg** [Theano/Theano#3693]
Particular combo makes test fail. Comments explain variations I tried.

```
import theano
import theano.tensor as T
from theano.ifelse import ifelse
import theano.tensor.nlinalg as nlinalg
from theano import function, config, shared, sandbox, Out, In, pp
floatX = config.floatX

import numpy as np
from numpy import *
import sys

config.mode = 'Mode'
config.optimizer = 'fast_run'
config.linker = 'c'
  #'cvm_nogc' #works on all variants

input0 = T.matrix()
input1 = T.vector()
A = input0

#out1 = A - input1[0]*identity(3)  #c linker fails
#out1 = A.dot(4.0 * identity(3))  #c linker works
out1 = input1[0] * identity(3) #c linker fails
out1 = A.dot(A) #c linker works

benchmark = function(
inputs=[input0, input1],
outputs=[out1],
on_unused_input='ignore')

normal_svd = array([[  5.93627687e+01  ,-4.66400725e-07  ,-2.56265154e-06],
 [ -4.66400725e-07   ,9.46869131e-01  ,-3.18862544e-02],
 [ -2.56265154e-06  ,-3.18862544e-02   ,1.05226779e+00]], dtype=floatX)

orientationi = array([ 59.36276866   ,1.06116353   ,0.93797339], dtype=floatX)

out1 = benchmark(normal_svd, orientationi)
```

Works on c:
```
out1 = 59.36*identity(3)
out1 = out1.dot(out1)
```
Fails on c:
```
out1 = input1[0]*identity(3)
out1 = out1.dot(out1)
```

Errors the same "Segmentation fault" and no line number etc. It seems like input1 & dot() combo fails, otherwise it runs.

Q2: Whenever 'c' does compile, I confirmed the cache files show 1 folder generated vs ~9 folders for 'cvm_nogc'. But the 'c' runtime is consistently slightly slower than 'cvm_nogc'. Does it have extra overheads to merge all the code into 1 file? I assumed 'c' avoids ping-ponging to numpy/py to save some overhead.

**Comment by nouiz** [comment]
Thanks for the report. The problem is related to our cache. if the cache is
empty, it work, otherwise it fail. I'm looking at it.

**Comment by nouiz** [comment]
I have a PR here: https://github.com/Theano/Theano/pull/3694

**Comment by gophercg** [comment]
To clarify, I ran `theano-cache clear` every time before running a linker 'c' script (otherwise it will fail with other errors). So with a clean compiledir, some of the above examples mentioned did run. Cvm does not require the clear command. I'm not sure the compiledir cache files is the same cache you mention.

Cool thanks! I'm not sure how to get updates from a pull request, and my PC has no internet. Do I simply replace the `cc.py` and `test_cc.py` files?

**Comment by nouiz** [comment]
you can just replace the cc.py file for now is you don't plan to run the
tests.

**Comment by nouiz** [comment]
The fix was merged in Theano. So if you update Theano, it should work.

thanks

**Comment by gophercg** [comment]
Thanks for the fast fix!
Replacing cc.py: I'm getting "Apply object has no attribute 'run_params'" errors. Seems my Theano's older, so I'll update at a later time. Thanks.

**Comment by nouiz** [comment]
I think this is a problem with mixed THeano version. Can you be sure to
update Theano and delete your cache?

**Comment by gophercg** [comment]
Sorry took awhile to resetup the crashed pc:
```
#previous theano version:
#>>> theano.version.version
#'0.7.0.dev-e617dc5087204d7bdb9eb10249b2d87fc73f5cec'

#upgraded/reinstalled latest dev theano.
#>>> print theano.version.version
#0.7.0.dev-e521b20e578c033d51e548181bd1edd24af64427
```

Ok `theano-cache clear` is no longer needed to run with 'c' linker.

Some previous test cases now works, but certain dot() lines still fail:
```
expr1 = A-input1[0]*identity(3)

#out1 = input1[0]*identity(3) #ok
#out1 = out1.dot(out1) #seg fault

#out1 = expr1 #ok
#out1 = expr1*expr1 #ok
#out1 = expr1.dot(expr1) #c fail
#out1 = A*A #ok
#out1 = A.dot(A) #ok
#out1 = A.dot(A) + w[1] #ok
#out1 = A.dot(A + w[1]) #ok
#out1 = A.dot(expr1) #ok
#out1 = expr1.dot(A) #seg fault
#out1 = expr1.dot(expr1) #seg fault
```
Can you reproduce results on your end? It's curious `A` (an original input) works on the left side of dot(), while a calculated symbol `expr1` fails on the left side.

**Comment by nouiz** [comment]
I got a new PR that fix those cases:

https://github.com/Theano/Theano/pull/3766

We didn't test heavily the c linker for a full Theano function. So you can find other cases like this. The fix is always similar to the one I just did.

Why do you want to use the c linker?

**Comment by nouiz** [comment]
We have a few different op on the CPU for dot. The 2 different cases used 2
different op and only one had a problem.

**Comment by gophercg** [comment]
A code I'm developing got only 3x Theano speedup compared to numpy. So was trying every linker/settings possible to improve it. If c linker isn't really faster than cvm then it's probably not worth fixing. Now I'm trying GPU, which seems to run. Thanks for the fixes though.
