### ISSUE TITLE
Illegal instruction when sharing home directory between computers

### ISSUE THREAD

**Issue by julianbrost** [Theano/Theano#4783]
We have a setup where the home directories are shared between multiple computers with different CPU generations. When first running theano on a machine with a recent CPU and then on one with an older CPU, this results in an invalid opcode trap:

```
haswell$ lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Stepping:              3
CPU MHz:               805.664
CPU max MHz:           3700.0000
CPU min MHz:           800.0000
BogoMIPS:              6585.27
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
haswell$ python -c 'import theano'

westmere$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Model name:            Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
Stepping:              2
CPU MHz:               1596.000
CPU max MHz:           2395.0000
CPU min MHz:           1596.0000
BogoMIPS:              4787.78
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-3,8-11
NUMA node1 CPU(s):     4-7,12-15
westmere$ python -c 'import theano'
[1]    1550 illegal hardware instruction (core dumped)  python -c 'import theano'
westmere$ dmesg | tail -1
[1877270.572252] traps: python[1550] trap invalid opcode ip:7f16940bab8c sp:7fff7608b270 error:0 in lazylinker_ext.so[7f16940b6000+6000]    
```

This happens because theano uses flags like `-march=native` when compiling:

```
$ strace -f -e execve python -c 'import theano' |& grep -F /usr/bin/g++ | grep -Fe -march
[pid  6445] execve("/bin/sh", ["/bin/sh", "-c", "/usr/bin/g++ -march=native -E -v"...], [/* 44 vars */]) = 0
[pid  6446] execve("/usr/bin/g++", ["/usr/bin/g++", "-march=native", "-E", "-v", "-"], [/* 44 vars */]) = 0
[pid  6451] execve("/usr/bin/g++", ["/usr/bin/g++", "-shared", "-g", "-march=haswell", "-mmmx", "-mno-3dnow", "-msse", "-msse2", "-msse3", "-mssse3", "-mno-sse4a", "-mcx16", "-msahf", "-mmovbe", "-maes", "-mno-sha", ...], [/* 44 vars */]) = 0
[pid  6457] execve("/usr/bin/g++", ["/usr/bin/g++", "-shared", "-g", "-march=haswell", "-mmmx", "-mno-3dnow", "-msse", "-msse2", "-msse3", "-mssse3", "-mno-sse4a", "-mcx16", "-msahf", "-mmovbe", "-maes", "-mno-sha", ...], [/* 44 vars */]) = 0
```

These modules are then cached in `.theano/compiledir_*` and break when imported on an older CPU.

Theano version is 0.8.2, operating system is Debian jessie.

**Comment by nouiz** [comment]
Can you try with the theano dev version? We have some fix related to that.
But we aren't sure we fixed everything:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

Delete your Theano cache to test this. If you still have problem, tell us,
I would like to find the missing cases.

Here we also have such a setup, but we don't have that problem, so it would
be caused by specific combination of CPU generation and maybe OS version.

**Comment by julianbrost** [comment]
Yes, this still happens with 0.9.0dev2.dev-e4e08782d3a10d010d3a99bc87fd0fc3b0465405. Which fix are you referring to?

**Comment by xuancong84** [comment]
Newer CPUs support higher-version AVX instruction sets (https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) for faster performance especially in matrix/vector/array operations. Whether to use these instructions is determined at package compilation time during Theano installation. Therefore, it is impossible to use the same installed copy of Theano on CPUs supporting different versions of AVX instruction sets.

So you have 2 choices:
1. install Theano using the old CPU. Drawback: the efficiency on newer CPU will be suboptimal as AVX optimizations will not be used
2. install a local copy of Theano on each computer. Drawback: very troublesome to manage Theano, need to synchronize Theano every time for every computer

**Comment by tastyminerals** [comment]
I think I've bumped into the same issue while trying to run **Theano** on university cluster machine via ssh.
Long story short, I access my remote machine via ssh and then I ssh again into a more powerful machine with the following CPU architecture:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             4
NUMA node(s):          8
Vendor ID:             AuthenticAMD
CPU family:            21
Model:                 2
Stepping:              0
CPU MHz:               2500.057
BogoMIPS:              5000.06
Virtualization:        AMD-V
L1d cache:             16K
L1i cache:             64K
L2 cache:              2048K
L3 cache:              6144K
NUMA node0 CPU(s):     0-7
NUMA node1 CPU(s):     8-15
NUMA node2 CPU(s):     32-39
NUMA node3 CPU(s):     40-47
NUMA node4 CPU(s):     48-55
NUMA node5 CPU(s):     56-63
NUMA node6 CPU(s):     16-23
NUMA node7 CPU(s):     24-31
```

I have a RNN script that crashes both on current **Theano dev** and **0.8.2** versions with **"Illegal instruction"** error. Here is a sample of the code where if fails.

```
# build the model: 2 stacked LSTM
print('Build model...')
model = Sequential()
model.add(LSTM(128, input_shape=(maxlen, len(chars))))  # <-- Illegal instruction!
model.add(Dense(len(chars)))
model.add(Activation('softmax'))
optimizer = RMSprop(lr=0.01)
model.compile(loss='categorical_crossentropy', optimizer=optimizer)
```

**Comment by xuancong84** [comment]
@tastyminerals I am not very sure about virtual environment as I have never used it. So on which machine did you compile & install Theano? Does it crash on that machine? If so, you may try installing without virtual env.

The physical location of the dir is not important. The difference between the compiling machine's CPU flags and the running machine's CPU flags is important. For example, if you compile on a machine with CPU1 supporting AVX2 instructions, and run it on a machine with CPU2 supporting only up to AVX, then all those AVX2 instructions (generated on CPU1 for maximal optimization) will cause illegal instruction error on CPU2.

Take note, there are two rounds of compilations. The first one happens when you install Theano. The 2nd one happens when you run your Theano code, where Theano compiles your expression graphs. Theano also has a cache for the 2nd compilation. If the cache folder is also shared on a cluster filesystem by all the machines, then it will cause problems. You can clear that cache using "theano-cache clear".

**Comment by tastyminerals** [comment]
Ok, here is what setup I have.
`ssh uni@login`
I loging into my **home machine** which contains `~/.bashrc`:
```
export HDF5="/home/CE/pavels/hdf518"
export PATH=$PATH:${HDF5}/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HDF5}/lib
export BLAS_PATH=/local/pavels/openblas_falken
export LD_LIBRARY_PATH=/local/pavels/openblas_falken/lib:$LD_LIBRARY_PATH
export LD_RUN_PATH="${BLAS_PATH}:${LD_RUN_PATH}"
```
This **home machine** uses the following cpu:
```Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            16
Model:                 2
Stepping:              3
CPU MHz:               2300.093
BogoMIPS:              4600.18
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              2048K
NUMA node0 CPU(s):     0,1
```
Where each cpu:
```
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 2
model name	: Quad-Core AMD Opteron(tm) Processor 2356
stepping	: 3
microcode	: 0x1000095
cpu MHz		: 2300.093
cache size	: 512 KB
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl tsc_reliable nonstop_tsc pni cx16 popcnt hypervisor lahf_lm extapic abm sse4a misalignsse 3dnowprefetch
bogomips	: 4600.18
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```
I am not working in this machine, it has only 2 cpu and 2GB of ram. Instead I login to some **power machines** `ssh power-machine-1`.

The **power-machine-1** has 64 CPU:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                64
On-line CPU(s) list:   0-63
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             4
NUMA node(s):          8
Vendor ID:             AuthenticAMD
CPU family:            21
Model:                 2
Stepping:              0
CPU MHz:               2500.057
BogoMIPS:              5000.06
Virtualization:        AMD-V
L1d cache:             16K
L1i cache:             64K
L2 cache:              2048K
L3 cache:              6144K
NUMA node0 CPU(s):     0-7
NUMA node1 CPU(s):     8-15
NUMA node2 CPU(s):     32-39
NUMA node3 CPU(s):     40-47
NUMA node4 CPU(s):     48-55
NUMA node5 CPU(s):     56-63
NUMA node6 CPU(s):     16-23
NUMA node7 CPU(s):     24-31
```
Each CPU is:
```
processor	: 63
vendor_id	: AuthenticAMD
cpu family	: 21
model		: 2
model name	: AMD Opteron(tm) Processor 6380                 
stepping	: 0
microcode	: 0x6000822
cpu MHz		: 2500.057
cache size	: 2048 KB
physical id	: 2
siblings	: 16
core id		: 7
cpu cores	: 8
apicid		: 79
initial apicid	: 79
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb arat cpb hw_pstate npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold bmi1
bogomips	: 5000.06
TLB size	: 1536 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro
```
This machine has 1TB of ram, 64 CPUs.  So, I run my code while being logged into the **power-machine-1**. However my script crashes with either `Illegal instruction` or 
```
ImportError: ('The following error happened while compiling the node', forall_inplace,cpu,scan_fn}(Shape_i{0}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, DeepCopyOp.0, Shape_i{0}.0, V, E, c, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0, Subtensor{int64}.0), '\n', 'The following error happened while compiling the node', CGemv{inplace}(AllocEmpty{dtype='float64'}.0, TensorConstant{1.0}, InplaceDimShuffle{x,0}.0, <TensorType(float64, vector)>, TensorConstant{0.0}), '\n', '/home/CE/pavels/.theano/compiledir_Linux-3.11--generic-x86_64-with-Ubuntu-12.04-precise-x86_64-2.7.3-64/tmpAEp8TK/596b3934be1f5ef760a5e620d56756c3.so: undefined symbol: _gfortran_st_write_done', '[CGemv{inplace}(<TensorType(float64, (True,))>, TensorConstant{1.0}, <TensorType(float64, row)>, <TensorType(float64, vector)>, TensorConstant{0.0})]')
```

`Illegal instruction` happens if I work under virtual environment and during execution of the script. So, the script starts, does some text preprocessing and even some matrix multiplication, but then at some point it crashes (I showed in my previous post when). Also, I can do logistic regression and run some Theano examples without `Illegal instruction` popping up. 
The second, import error appears when I install everything locally via **easy_install --user pipy-package.tar.gz**. The packages are getting installed into `~/.local/` folder which is physically on **home machine**.

I already tried using cxxflags like "native", "avx", "avx2", "core" and anything I could google out. Removing `~/.theano` folder and installing everything back. Removing complete `~/.local/lib` abd reinstalling everything back, nothing helped. I get `Illegal instruction` when I run my RNN script and I get import error if I run this script not in virtual environment (I run the script only when I am logged into the **power-machine-1**). The same exact script runs without any errors on my i5 core Archlinux laptop. As mere users we do not have **sudo access** to our university machines, we are allowed to *do stuff* locally (that is why I compiled new openblas, hdf5 and set their respective new paths). At this point I am literally out of ideas how to run Theano on such setup. Should I say that **torch** works without issues under the same configuration.

**Comment by xuancong84** [comment]
If Theano installation is really so troublesome for your setup, my suggestions would be: go for Torch or Tensorflow.
In fact, I have recently discovered that Theano does not perform calculations correctly for arbitrary complex network structures, [https://github.com/Theano/Theano/issues/4770], despite the fact that it runs much faster than Tensorflow.

**Comment by tastyminerals** [comment]
Yep, I guess there is no other way :(

**Comment by lamblin** [comment]
A simple workaround would be to have separate compiledirs for different architectures, which you can specify in the .theanorc file or THEANORC environment variable.
I'm really surprised that setting `gcc.cxxflags=core2` or `gcc.cxxflags=i686` then calling `theano-cache purge` (or removing `.theano/`) does not solve the issue.

**Comment by tastyminerals** [comment]
I tried using `.theanorc`
```
[gcc]
cxxflags = core2
```
and got 
```
Exception: Compilation failed (return status=1): g++: error: native: No such file or directory.
```

**Comment by tastyminerals** [comment]
**Finally I fixed it!** A guy working with Theano helped me on that.
So, all you need is to:
```
$ export THEANO_FLAGS='blas.ldflags=-lblas -lgfortran'
```
And run your file afterwards.
Better put this into `~/.bashrc`.

**Comment by FiringBird** [comment]
Hi,I have just install the theano 0.8.2 on my linux machine which the os is "Linux test-60-11 2.6.32-220.23.2.ali878.el6.x86_64 #1 SMP Mon Jan 28 17:12:52 CST 2013 x86_64 x86_64 x86_64 GNU/Linux", however, when I try to import theano, it ouccurs the error "illegal instructuion", I also have tried reinstall with the version 0.6, it can been imported successfully. So how can I import theano of 0.8.2 successfully on my machine? Who can help me , please!

**Comment by nouiz** [comment]
I think we have fixed that in the master of Theano. Update to it. Delete your Theano cache.

I'll close this issue. If you still have problems with the master of Theano, open a new issue.

**Comment by nouiz** [comment]
I went too fast, we didn't fix it when the cache is on NFS with computer with big difference in CPU.

**Comment by lamblin** [comment]
Since we removed most of the code inside cutils_ext, and that we do not have an unversioned cuda_ndarray any more, maybe we can just compile cutils_ext without arch optimizations.
