### ISSUE TITLE
Merge optimizer generate error.

### ISSUE THREAD

**Issue by nouiz** [Theano/Theano#5319]
See https://github.com/fchollet/keras/issues/4001#issuecomment-264414466

I'm able to reproduce the problem.

**Comment by lamblin** [comment]
This is not the first time something similar happens.
The underlying issue is that we try to infer the broadcasting pattern of the output using shape inference (to see if a shape is 1), and that more information becomes available during the optimization process.
So if two Reshape nodes, for instance, have the same inputs, but one had not been determined to be 1 when it was built, and the other was, then their output broadcasting pattern would be different.

The easier option to avoid the error would be to add the output broadcasting pattern as a `prop` of `Reshape`. That way, the merge would not be attempted.
Then, we could replace `Reshape{False}(...)` by `Reshape{True}(...).unbroadcast()` if we later have more information and really want not to duplicate the reshape operation.

**Comment by lamblin** [comment]
I tried adding props to `Reshape`, and it is not as easy as I thought, in particular if we want to be able to reload old pickles, and because `ndim` is already a prop.
Also, I was not able to reproduce the issue on CPU alone.

For now, I think the quickest fix for the issue with GpuReshape may be to add an optimization replacing `GpuReshape(...)` by `GpuReshape(...).unbroadcast()` if we infer that the output should be broadcastable given the shape but is not (by building a new GpuReshape Apply node).

**Comment by nouiz** [comment]
@lamblin I don't understand why this will help. If the graph end up at any point with 2 reshape of the same input that give different output, then we have a problem. So we should:

1) Find the current and all possible creation of GpuReshape (and all other ops like that) make modify them to look into the graph if we have such reshape already existing and reuse that output broadcast pattern.
2) Modify MergeOptimizer to add a patternbroadcast() to one of the input before merging.
3) Be less strict and allow to add broadcastable dimensions during the graph optimization.

I think 1) is impossible to maintain and very hard to do. I think 3) is a pandora box and we want to replace all the broadcast stuff by shape inference, so it would go away anyway.

So the only fix left is 2. Do you see other options?

**Comment by nouiz** [comment]
After a long discussion with @lamblin here is the plan of how to fix it.

In the MergeOptimizer, make a try..except around the replacement call to the fgraph.  If a TypeError is raised, catch it. In the except:
- Assert the type(x) of both variable are the same. If False, then reraise
- Check that both have a dtype and ndim field and they are the same. If False, then reraise
- Check both have a broadcastable field and they aren't the same. If False, then reraise.
- Choose the variable that will survive in the graph like this: between the two variable we replace the one with the less number of non-broadcastable dimensions. Assert that this variable non-broadcastable dimensions are non-broadcastable in the other variable.
- Then unbroadcast the selected variable to the pattern of the non-selected variable
- Replace the non-selected variable by this one in the graph.

As this is sensitive code, we will want more test. When the example that generate the error pass, check:
- All Theano tests pass (CPU and both GPU back-end)
- All DLT tests
- We need to speed test this change to make sure it don't cause speed regression. To do so, take this example with a minibatch size of 2. Time the compilation phase before and after this fix. It should be the same. Time again with batch size of 1 with the fix. Should be very close to the compilation time with minibatch size of 2.

Also, do this only for variables where the owner is Reshape or GpuShape for now. Later, we will extend this to [Gpu]Alloc[Empty]

**Comment by nouiz** [comment]
fixed.

**Comment by Spaak** [comment]
I suspect I'm suffering from the same problem. I'm on the master branch (just pulled all changes from github), so the fix might not have fixed everything. I'm getting:

```
<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{2}.0, Reshape{2}.0, TensorType(float32, row), TensorType(float32, matrix), 'local_reshape_dimshuffle') local_reshape_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_reshape_dimshuffle
Optimization failure due to: local_reshape_dimshuffle
ERROR (theano.gof.opt): node: Reshape{2}(InplaceDimShuffle{x,0}.0, <TensorType(int64, vector)>)
node: Reshape{2}(InplaceDimShuffle{x,0}.0, <TensorType(int64, vector)>)
ERROR (theano.gof.opt): TRACEBACK:
TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/eelke/repos/Theano/theano/gof/opt.py", line 2022, in process_node
    remove=remove)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/eelke/repos/Theano/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{2}.0, Reshape{2}.0, TensorType(float32, row), TensorType(float32, matrix), 'local_reshape_dimshuffle')

Traceback (most recent call last):
  File "/home/eelke/repos/Theano/theano/gof/opt.py", line 2022, in process_node
    remove=remove)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/eelke/repos/Theano/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{2}.0, Reshape{2}.0, TensorType(float32, row), TensorType(float32, matrix), 'local_reshape_dimshuffle')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{3}.0, Reshape{3}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_reshape_dimshuffle') local_reshape_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_reshape_dimshuffle
Optimization failure due to: local_reshape_dimshuffle
ERROR (theano.gof.opt): node: Reshape{3}(InplaceDimShuffle{x,0}.0, <TensorType(int64, vector)>)
node: Reshape{3}(InplaceDimShuffle{x,0}.0, <TensorType(int64, vector)>)
ERROR (theano.gof.opt): TRACEBACK:
TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/eelke/repos/Theano/theano/gof/opt.py", line 2022, in process_node
    remove=remove)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)

  File "/home/eelke/repos/Theano/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{3}.0, Reshape{3}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_reshape_dimshuffle')

Traceback (most recent call last):
  File "/home/eelke/repos/Theano/theano/gof/opt.py", line 2022, in process_node
    remove=remove)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/eelke/repos/Theano/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{3}.0, Reshape{3}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_reshape_dimshuffle')

<<!! BUG IN FGRAPH.REPLACE OR A LISTENER !!>> <class 'TypeError'> ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{3}.0, Reshape{3}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_reshape_dimshuffle') local_reshape_dimshuffle
ERROR (theano.gof.opt): Optimization failure due to: local_reshape_dimshuffle
Optimization failure due to: local_reshape_dimshuffle
ERROR (theano.gof.opt): node: Reshape{3}(InplaceDimShuffle{x,0}.0, <TensorType(int64, vector)>)
node: Reshape{3}(InplaceDimShuffle{x,0}.0, <TensorType(int64, vector)>)
ERROR (theano.gof.opt): TRACEBACK:
TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/eelke/repos/Theano/theano/gof/opt.py", line 2022, in process_node
    remove=remove)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/eelke/repos/Theano/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{3}.0, Reshape{3}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_reshape_dimshuffle')

Traceback (most recent call last):
  File "/home/eelke/repos/Theano/theano/gof/opt.py", line 2022, in process_node
    remove=remove)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 391, in replace_all_validate_remove
    chk = fgraph.replace_all_validate(replacements, reason)
  File "/home/eelke/repos/Theano/theano/gof/toolbox.py", line 340, in replace_all_validate
    fgraph.replace(r, new_r, reason=reason, verbose=False)
  File "/home/eelke/repos/Theano/theano/gof/fg.py", line 481, in replace
    str(reason))
TypeError: ('The type of the replacement must be compatible with the type of the original Variable.', Reshape{3}.0, Reshape{3}.0, TensorType(float32, (True, False, False)), TensorType(float32, 3D), 'local_reshape_dimshuffle')
```

Everything runs fine (and even seems quite fast), but it's still an issue of course.

**Comment by ReyhaneAskari** [comment]
Can you give us a simple code that reproduces this? If sharing a code is hard, you could also
give us a function_dump:

http://deeplearning.net/software/theano/library/compile/function.html#theano.compile.function.function_dump

Thanks.

**Comment by Spaak** [comment]
@ReyhaneAskari sharing the code is a bit tricky, but here is the function dump that generates the error:
https://dl.dropboxusercontent.com/u/4023322/theano-funcdump.pkl

**Comment by ReyhaneAskari** [comment]
thanks @Spaak for the function dump. So you are using python 3 with pymc3. Is it possible to let me know what is the version of pymc3 that you are using. I installed it but I get this error:
```ImportError: No module named 'analysis_bayes'```. Are you using any other external libraries? 
Thanks,
Reyhane

**Comment by Spaak** [comment]
@ReyhaneAskari That's not an external library, it's one of my own modules. I was expecting the `function_dump` to alleviate the need for providing my own code :) The dependencies are quite extensive, unfortunately, and sorting them out will take too much time for me now. Is there any other way I can help you, by generating a debug dump or print or so?

**Comment by nouiz** [comment]
We don't need all your dependences, we should only need the one that
include the ops you implemented. Is that feasible?

I just re-read the code and found something interresting. Maybe this new
error will give us the information we have. Can you apply manually this
diff and send us the new error message?

diff --git a/theano/gof/fg.py b/theano/gof/fg.py
index 38876c8..619d1fa 100644
--- a/theano/gof/fg.py
+++ b/theano/gof/fg.py
@@ -15,6 +15,7 @@ from theano.gof import toolbox
 from theano import config

 from six import iteritems, itervalues
+from six.moves import StringIO
 from theano.gof.utils import get_variable_trace_string
 from theano.misc.ordered_set import OrderedSet
 NullType = None
@@ -468,10 +469,24 @@ class FunctionGraph(utils.object2):
             new_r2 = r.type.convert_variable(new_r)
             # We still make sure that the type converts correctly
             if new_r2 is None or new_r2.type != r.type:
-                raise TypeError("The type of the replacement must be "
-                                "compatible with the type of the original "
-                                "Variable.", r, new_r, r.type, new_r.type,
-                                str(reason))
+                done = dict()
+                used_ids = dict()
+                old = theano.compile.debugmode.debugprint(
+                    r, prefix='  ', depth=6,
+                    file=StringIO(), done=done,
+                    print_type=True,
+                    used_ids=used_ids).getvalue()
+                new = theano.compile.debugmode.debugprint(
+                    new_r, prefix='  ', depth=6,
+                    file=StringIO(), done=done,
+                    print_type=True,
+                    used_ids=used_ids).getvalue()
+                raise theano.compile.debugmode.BadOptimization(
+                    r, new_r, None, None, reason, old, new)
+                raise TypeError("The type of the replacement (%s) must be "
+                                "compatible with the type of the original
(%s) "
+                                "Variable.", r.type, new_r.type,
+                                str(reason), '\n', old, '\n', new)
             new_r = new_r2
         if r not in self.variables:
             # this variable isn't in the graph... don't raise an

**Comment by nouiz** [comment]
Your error seem to be the one in this issue, not the current issue. Can you
move the rest of the discussion there?

https://github.com/Theano/Theano/issues/5392
