### ISSUE TITLE
After upgrading to 0.9.0b1 training never starts | theano.test() fails

### ISSUE THREAD

**Issue by subzerofun** [Theano/Theano#5560]
OS: MacOS Sierra 10.12
GPU: GTX 780
CUDA: 8.0, Cudnn 5.1

Installed the newest theano and libgpuarray versions from source, compiled libgpuarray without errors.

Was trying to run this project:
**Keras WaveNet implementation**
https://github.com/basveeling/wavenet

But after showing the model in the terminal output the training never starts and just quits after 2-5min doing nothing. I'm sure that the code is OK and something is wrong on my side.

I have the exact same problem with another project, the training simply never starts...
https://github.com/MattVitelli/GRUV
**As soon as i switch back to Theano 0.8.2 this project is working again.** 

But a lot of people are building their new projects on Theano >0.9 and unfortunately i can’t run them with Theano 0.8.2.

I checked the free memory on my card, it was around 3-4 GB (from 6GB) – this should be enough. And if that was the problem i would see a memory allocation error somewhere.

The first example from http://deeplearning.net/software/theano/tutorial/using_gpu.html
only works with the flags `THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32`
when i try to change `device` to `cuda` or `cuda0` the cpu is used.

Example nr.2 and 3 works with `device=cuda` – the gpu is being used.

---
### Theano Tests crash

I then tried `theano.test()` and this is the output:
```
Python 2.7.12 (default, Oct 11 2016, 05:20:59)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import theano
Using cuDNN version 5105 on context None
Mapped name None to device cuda: GeForce GTX 780 (0000:01:00.0)
>>> theano.test()
Theano version 0.9.0beta1.dev-8757c2dc05a86ba0e8ff0febb0cd415183da434a
theano is installed in /usr/local/lib/python2.7/site-packages/theano
NumPy version 1.12.0
NumPy relaxed strides checking option: True
NumPy is installed in /usr/local/lib/python2.7/site-packages/numpy
Python version 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
nose version 1.3.7
/usr/local/lib/python2.7/site-packages/theano/sandbox/gpuarray/__init__.py:10: UserWarning: theano.sandbox.gpuarray has been moved to theano.gpuarray. Please update your code and pickles. If the warning persists, clear theano's cache ('$theano/bin/theano-cache clear').
  warnings.warn(message)
...................................S.........................................S........................../usr/local/lib/python2.7/site-packages/theano/compile/nanguardmode.py:154: RuntimeWarning: All-NaN slice encountered
  return np.isinf(np.nanmax(arr)) or np.isinf(np.nanmin(arr))
/usr/local/lib/python2.7/site-packages/theano/compile/nanguardmode.py:154: RuntimeWarning: All-NaN axis encountered
  return np.isinf(np.nanmax(arr)) or np.isinf(np.nanmin(arr))
..............................................EE.........SS.............0.0581646137166
0.0581646137166
0.0581646137166
0.0581646137166
........................................................................................................................................................../usr/local/lib/python2.7/site-packages/theano/gof/vm.py:870: UserWarning: LoopGC does not support partial evaluation, using Stack VM.
  'LoopGC does not support partial evaluation, '
...F...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...............S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..................Segmentation fault: 11
```

And another error from the second run:
```
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{[[ 7.]
 [ 8.]]})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1973, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 6446, in constant_folding
    no_recycling=[], impl=impl)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1575, in cthunk_factory
    key = self.cmodule_key()
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1270, in cmodule_key
    header_dirs=self.header_dirs(),
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1043, in header_dirs
    ret += x.c_header_dirs()
  File "/usr/local/lib/python2.7/site-packages/theano/gpuarray/type.py", line 494, in c_header_dirs
    if os.path.exists(alt_inc_dir) and os.path.isdir(alt_inc_dir):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: stat() argument 1 must be encoded string without null bytes, not str

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{[[ 7.]
 [ 8.]]})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/theano/gof/opt.py", line 1973, in process_node
    replacements = lopt.transform(node)
  File "/usr/local/lib/python2.7/site-packages/theano/tensor/opt.py", line 6446, in constant_folding
    no_recycling=[], impl=impl)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1575, in cthunk_factory
    key = self.cmodule_key()
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1270, in cmodule_key
    header_dirs=self.header_dirs(),
  File "/usr/local/lib/python2.7/site-packages/theano/gof/cc.py", line 1043, in header_dirs
    ret += x.c_header_dirs()
  File "/usr/local/lib/python2.7/site-packages/theano/gpuarray/type.py", line 494, in c_header_dirs
    if os.path.exists(alt_inc_dir) and os.path.isdir(alt_inc_dir):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: stat() argument 1 must be encoded string without null bytes, not str

ESegmentation fault: 11
```

So the tests don't run till the end, the python process abruptly crashes with `Segmentation fault: 11`

I have tried to uninstall theano, libgpuarray and keras, cleaned all older versions i could find (also the .theano folder in my home directory). Then reinstalled everything from source, but the problem still persists...

I hope someone can help me to find out what’s wrong with my installation!

**Comment by abergeron** [comment]
From what I can tell on my machine it's not doing nothing, it's compiling the graph.  The output is confusing because it says 
```
<other things>
INFO - main - Compiling Model...
INFO - main - Starting Training...
```
Where it is in fact compiling the Theano graph at this stage.  You can confirm this by running top in another terminal while it is doing "nothing" and see that there are regular invocations of g++ (or clang++ in your case).  It eventually finishes and I get to the actual training phase.

One thing that might not play in your favor, is that with the jump from 0.8 to 0.9 you pretty much have to recompile every node in the graph and that can take a long time.  Also, compile times are bigger on mac since clang++ is a wrapper script which will check if you accepted the xcode license and then run the real clang binary every time you invoke it.

**Comment by lamblin** [comment]
The segmentation fault may have been fixed by #5552 or #5561, which were merged recently. Could you try with the latest master?

The examples at http://deeplearning.net/software/theano/tutorial/using_gpu.html are for the 0.8 branch of Theano, and fail to detect that Theano is actually using the new back-end when running with `device=cuda`. You can verify that by seeing that the execution time is lower, and the graph contains `GpuElemwise` and `GpuArrayType`.
The updated example at http://deeplearning.net/software/theano_versions/dev/tutorial/using_gpu.html#testing-theano-with-gpu prints the right diagnosis ("Used the gpu") at the end.

**Comment by subzerofun** [comment]
Thanks for the feedback and the explanation of the example-tests.

Have updated, cleared and reinstalled theano, cleared my theano.rc file, reinstalled keras and tried the wavenet project again.
clang is working in the background, but the script still crashes after that. I should have said that before - it's not the case that nothing happens, it's just that i don't see any visible training progress until it crashes...

And that happens with both projects and as i mentioned at least the GRUV-LSTM works with Theano 0.8.2

### That's the output from the wavenet code:
```
(... all the model structure output ...)
INFO - main - None
INFO - main - Compiling Model...
INFO - main - Starting Training...
ERROR - wavenet - Failed after 0:00:23!
Traceback (most recent calls WITHOUT Sacred internals):
  File "wavenet.py", line 530, in main
    verbose=keras_verbose)
  File "/usr/local/lib/python2.7/site-packages/Keras-1.2.2-py2.7.egg/keras/engine/training.py", line 1463, in fit_generator
    raise ValueError('When using a generator for validation data, '
ValueError: When using a generator for validation data, you must specify a value for "nb_val_samples"
```

### And this happens with the https://github.com/MattVitelli/GRUV project:
```
Problem occurred during compilation with the command line below:
/usr/bin/clang++ -dynamiclib -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -L/usr/local/lib -L/Developer/NVIDIA/CUDA-8.0/lib/ -march=sandybridge -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -undefined dynamic_lookup -I/usr/local/lib/python2.7/site-packages/numpy/core/include -I/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/Users/myusername/github/neural-resources/Theano/theano/gof -L/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib -fvisibility=hidden -o /Users/myusername/.theano/compiledir_Darwin-16.0.0-x86_64-i386-64bit-i386-2.7.12-64/tmpZaCUxP/c6acccb2fd68eac67ca5b0f0fb9ad9bb.so /Users/myusername/.theano/compiledir_Darwin-16.0.0-x86_64-i386-64bit-i386-2.7.12-64/tmpZaCUxP/mod.cpp
/Users/myusername/.theano/compiledir_Darwin-16.0.0-x86_64-i386-64bit-i386-2.7.12-64/tmpZaCUxP/mod.cpp:894:21: warning: comparison of array 'outputs' equal to a null pointer is always false [-Wtautological-pointer-compare]
                if (outputs == NULL) {
                    ^~~~~~~    ~~~~
/Users/myusername/.theano/compiledir_Darwin-16.0.0-x86_64-i386-64bit-i386-2.7.12-64/tmpZaCUxP/mod.cpp:919:54: error: arithmetic on a pointer to void
                                    PyArray_DATA(V3) + data_offset,
                                    ~~~~~~~~~~~~~~~~ ^
1 warning and 1 error generated.
Traceback (most recent call last):
  File "train.py", line 53, in <module>
    history = model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=epochs_per_iter, verbose=1, validation_split=0.0)
  File "/usr/local/lib/python2.7/site-packages/Keras-1.2.2-py2.7.egg/keras/models.py", line 672, in fit
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/site-packages/Keras-1.2.2-py2.7.egg/keras/engine/training.py", line 1168, in fit
    self._make_train_function()
  File "/usr/local/lib/python2.7/site-packages/Keras-1.2.2-py2.7.egg/keras/engine/training.py", line 767, in _make_train_function
    **self._function_kwargs)
  File "/usr/local/lib/python2.7/site-packages/Keras-1.2.2-py2.7.egg/keras/backend/theano_backend.py", line 969, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/Keras-1.2.2-py2.7.egg/keras/backend/theano_backend.py", line 955, in __init__
    **kwargs)
  File "/Users/myusername/github/neural-resources/Theano/theano/compile/function.py", line 326, in function
    output_keys=output_keys)
  File "/Users/myusername/github/neural-resources/Theano/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/Users/myusername/github/neural-resources/Theano/theano/compile/function_module.py", line 1795, in orig_function
    defaults)
  File "/Users/myusername/github/neural-resources/Theano/theano/compile/function_module.py", line 1661, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/vm.py", line 1063, in make_all
    impl=impl))
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1586, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cmodule.py", line 1155, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1489, in compile_cmodule
    preargs=preargs)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cmodule.py", line 2309, in compile_str
    (status, compile_stderr.replace('\n', '. ')))
Exception: ('The following error happened while compiling the node', Split{4}(InplaceDimShuffle{1,0,2}.0, TensorConstant{2}, TensorConstant{(4,) of 2048}), '\n', "Compilation failed (return status=1): /Users/myusername/.theano/compiledir_Darwin-16.0.0-x86_64-i386-64bit-i386-2.7.12-64/tmpZaCUxP/mod.cpp:894:21: warning: comparison of array 'outputs' equal to a null pointer is always false [-Wtautological-pointer-compare].                 if (outputs == NULL) {.                     ^~~~~~~    ~~~~. /Users/myusername/.theano/compiledir_Darwin-16.0.0-x86_64-i386-64bit-i386-2.7.12-64/tmpZaCUxP/mod.cpp:919:54: error: arithmetic on a pointer to void.                                     PyArray_DATA(V3) + data_offset,.                                     ~~~~~~~~~~~~~~~~ ^. 1 warning and 1 error generated.. ", '[*1 -> Split{4}(<TensorType(float32, 3D)>, TensorConstant{2}, TensorConstant{(4,) of 2048}), *1::1, *1::2, *1::3]')
```

### And the theano.test() still crashes with segmentation fault:
```
>>> import theano
>>> theano.test()
Theano version 0.9.0beta1.dev-unknown-git
theano is installed in /Users/myusername/github/neural-resources/Theano/theano
NumPy version 1.12.0
NumPy relaxed strides checking option: True
NumPy is installed in /usr/local/lib/python2.7/site-packages/numpy
Python version 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
nose version 1.3.7
Using cuDNN version 5105 on context None
Preallocating 1228/6143 Mb (0.200000) on cuda
Mapped name None to device cuda: GeForce GTX 780 (0000:01:00.0)
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX 780 (CNMeM is disabled, cuDNN 5105)
/Users/myusername/github/neural-resources/Theano/theano/sandbox/gpuarray/__init__.py:10: UserWarning: theano.sandbox.gpuarray has been moved to theano.gpuarray. Please update your code and pickles. If the warning persists, clear theano's cache ('$theano/bin/theano-cache clear').
  warnings.warn(message)
.............................................................................S........................../Users/myusername/github/neural-resources/Theano/theano/compile/nanguardmode.py:154: RuntimeWarning: All-NaN slice encountered
  return np.isinf(np.nanmax(arr)) or np.isinf(np.nanmin(arr))
/Users/myusername/github/neural-resources/Theano/theano/compile/nanguardmode.py:154: RuntimeWarning: All-NaN axis encountered
  return np.isinf(np.nanmax(arr)) or np.isinf(np.nanmin(arr))
..............................................EE.........SS.............0.0581646137166
0.0581646137166
0.0581646137166
0.0581646137166
........................................................................................................................................................../Users/myusername/github/neural-resources/Theano/theano/gof/vm.py:870: UserWarning: LoopGC does not support partial evaluation, using Stack VM.
  'LoopGC does not support partial evaluation, '
...F...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...............S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S.S................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..............SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..................ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{[[ 7.]
 [ 8.]]})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/opt.py", line 1973, in process_node
    replacements = lopt.transform(node)
  File "/Users/myusername/github/neural-resources/Theano/theano/tensor/opt.py", line 6446, in constant_folding
    no_recycling=[], impl=impl)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1575, in cthunk_factory
    key = self.cmodule_key()
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1270, in cmodule_key
    header_dirs=self.header_dirs(),
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1043, in header_dirs
    ret += x.c_header_dirs()
  File "/Users/myusername/github/neural-resources/Theano/theano/gpuarray/type.py", line 494, in c_header_dirs
    if os.path.exists(alt_inc_dir) and os.path.isdir(alt_inc_dir):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: stat() argument 1 must be encoded string without null bytes, not str

ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: GpuFromHost<None>(TensorConstant{[[ 7.]
 [ 8.]]})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/opt.py", line 1973, in process_node
    replacements = lopt.transform(node)
  File "/Users/myusername/github/neural-resources/Theano/theano/tensor/opt.py", line 6446, in constant_folding
    no_recycling=[], impl=impl)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1575, in cthunk_factory
    key = self.cmodule_key()
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1270, in cmodule_key
    header_dirs=self.header_dirs(),
  File "/Users/myusername/github/neural-resources/Theano/theano/gof/cc.py", line 1043, in header_dirs
    ret += x.c_header_dirs()
  File "/Users/myusername/github/neural-resources/Theano/theano/gpuarray/type.py", line 494, in c_header_dirs
    if os.path.exists(alt_inc_dir) and os.path.isdir(alt_inc_dir):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: stat() argument 1 must be encoded string without null bytes, not str

ESegmentation fault: 11
```


With Theano 0.8.2 (installed with pip) the tests complete successfully.

**Sorry for the long terminal output logs, but i thought maybe someone would see an obvious error.**

**Comment by subzerofun** [comment]
OK update: I always tried to install the bleeding edge version (because of all the quickly implemented fixes) and then decided to try the `pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git` method and for some reason both projects work now!

I don't know what the pip install did differently, but it apparently fixed my problems 🎉 !

Only downside is that for the GRUV-LSTM code the loading (graph compiling?) before the training starts takes quite a while compared to 0.8.2. The processes cudafe, cudafe++, nvcc and clang need 2-3min before the training starts.

So one last question, then i'll close this: Is there anything i can do to speed this up?

**Comment by lamblin** [comment]
Thanks for confirming that it works with the latest version from GitHub.
After a version update, it is not unusual for the first training to take longer, as some code has to be regenerated and recompiled. For subsequent runs of the same scripts, the loading time should be shorter.
We are aware that the new GPU back-end will recompile some kernels each time a new process is launched (the old back-end cached more things), but we are working on that.

**Comment by leocnj** [comment]
A segway question:

@subzerofun I have almost the same setup as yours

> OS: MacOS Sierra 10.12
> GPU: GTX 750M (on a MBP)
> CUDA: 8.0.64, Cudnn 5.1

I just used conda and installed theano to its 0.9 version. Though the same OS/GPU setup works well when using Tensorflow, it fails when using GPU in theano. Just got such error

> WARNING (theano.sandbox.cuda): CUDA is installed, but device gpu is not available  (error: cuda unavailable)

Just curious whether you have met up the same error during your toolkit installation.

**Comment by subzerofun** [comment]
@leocnj Hmm.. I've only had problems with Theano not finding my GPU before because of wrong settings in `.theanorc`. But maybe it's a little bit different for you because your MacBook also has an internal GPU (on the CPU) and the GTX750M. I've disabled my Intel GPU because of driver issues, but i don't use a Macbook. I've built a custom machine, a "hackintosh": i7 2600k @ 4,4Ghz, 24GB RAM + GTX 780 6GB VRAM. But i'll still try my best to help :-)

---

### Check CUDA device and drivers
Can you run the `deviceQuery` binary (attached below) in Terminal and post your output? The file is from the official Nvidia CUDA Toolkit examples: http://docs.nvidia.com/cuda/cuda-samples/#device-query and checks your card capabilities, specs and installed drivers.

[deviceQuery.zip](https://github.com/Theano/Theano/files/886649/deviceQuery.zip)

[CUDA-Z](http://cuda-z.sourceforge.net/) is also a nice OSX tool for checking your GPU.

I guess this is probably redundant because Tensorflow + GPU is working for you.

---
### Theano version & libgpuarray

Have you tried the "bleeding edge" version of Theano?
I always uninstall everything with `pip uninstall theano` before i try a new install.
http://deeplearning.net/software/theano/install_macos.html#bleeding-edge-installation-recommended
`sudo pip install git+https://github.com/Theano/Theano.git#egg=Theano`

Have you installed and tested libgpuarray?
 http://deeplearning.net/software/libgpuarray/installation.html

---

**Theano flags**
Could you check if you have the file `/Users/YOU/.theanorc`? And if yes, what's the content?

This is my `.theanorc` (ignore the disabled lines with "#"):
```
[global]
floatX = float32
device = gpu
force_device = True
allow_gc= True
print_active_device = True
#enable_initial_driver_test = True
#profile_memory = True
#profile_optimizer = True
#optimizer_verbose = True
exception_verbosity=high

[gpuarray]
#preallocate=0.8 #disabled because it doesn't work as intended

[dnn]
enabled = True

[gcc]
cxxflags = -L/usr/local/lib -L/Developer/NVIDIA/CUDA-8.0/lib/
#cxxflags = -L/usr/local/lib -L/Developer/NVIDIA/CUDA-7.5/lib/ #<- For CUDA 7.5

[nvcc]
fastmath = True
compiler_bindir=/usr/bin/clang
optimizer_including=cudnn

[cuda]
root = /Developer/NVIDIA/CUDA-8.0
#root = /Developer/NVIDIA/CUDA-7.5 #<- For CUDA 7.5

[blas]
#ldflags = -L/usr/local/opt/openblas/bin -lopenblas #disabled because of problems with openblas

[lib]
#cnmem=.8 #only works sometimes, disabled
#cnmem=1024 #amount of reserved VRAM in MB
```
Read more about the settings here: http://deeplearning.net/software/theano/library/config.html

---

### Bash profile

You need to export your .theanorc path in your .bash_profile:
```
# Theano
export THEANORC="/Users/YOU/.theanorc:$THEANORC"
```

I also have these settings for my CUDA install paths:
```
# Theano and CUDA
PATH="/Developer/NVIDIA/CUDA-8.0/bin:$PATH"
export LD_LIBRARY_PATH="/Developer/NVIDIA/CUDA-8.0/lib":$LD_LIBRARY_PATH
export CUDA_ROOT=/Developer/NVIDIA/CUDA-8.0
```

Then load the env variables again with `source ~/.bash_profile`

You can also export your Theano flags like this:
`THEANO_FLAGS='floatX=float32,device=cuda0'  python <myscript>.py`

But that's only for quick testing or if your .theanorc doesn't get loaded (had this issue a few times).

Before you create your own file try to export the flags and maybe change device "`cuda0`" to "`gpu`" or "`gpu0`" (maybe "`gpu1`" because of Intel Graphics?) if theano doesn't find your card.

Do you get any other errors like "deprecated backend" etc.?

**Can you try the steps and test examples** from here
http://deeplearning.net/software/theano/tutorial/using_gpu.html
http://deeplearning.net/software/theano/troubleshooting.html#mac-os
and see if it brings you more insight about the problem?

[deviceQuery.zip](https://github.com/Theano/Theano/files/886649/deviceQuery.zip)

You could post the output of the training examples – maybe we'll find a solution through the error messages.

Hope there is something here that helps you!

**Comment by lamblin** [comment]
> We are aware that the new GPU back-end will recompile some kernels each time a new process is launched (the old back-end cached more things), but we are working on that.

This has been done and is present in the latest releases of libgpuarray, so I'm closing this one.
